name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pandas=2.3.2
  - scikit-learn=1.7.2
  - pip=24.3.1
  - pip:
      - mlflow==3.3.2
      - wandb==0.21.3